[[redirects]]
  from = "/api/proxy"
  to = ":url"
  status = 200
  force = true
  query = { url = ":url" }
  headers = { 
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,OPTIONS"
    Access-Control-Allow-Headers = "Range,Content-Type"
  }